version: '3.8'
services:
  rate-book-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: AmirReza
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - MYWORKOUTS
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: AmirReza
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - MYWORKOUTS
networks:
  MYWORKOUTS:
